default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 010902
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: Web_Ruby_Rails-Learn_janpanese

production:
  <<: *default
  database: Web_Ruby_Rails-Learn_janpanese